version: '3.8'
services:
  petplatform:
    image: petplatform:latest
    volumes:
      - ./db:/app/db
      - ./data:/app/data
      - ./logs:/app/logs
      - ./parties:/app/parties
    environment:
      - TZ=Asia/Shanghai
      - PARTY=party_a
    ports:
      - "1234:1234"
